from ActFunctions.ActFunction import ActFunction
from ActFunctions.APL import APL
from ActFunctions import arctan
from ActFunctions.BentIdentity import BentIdentity
from ActFunctions.ELU import ELU
from ActFunctions.Gaussian import Gaussian
from ActFunctions.identity import identity
from ActFunctions.leakyRELu import LeakyReLU
from ActFunctions.PRelU import PReLU
